// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace swimming.Migrations
{
    [DbContext(typeof(MVCSwimmingContext))]
    partial class MVCSwimmingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("swimming.Models.Swimming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolCapacity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolLength")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PoolSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolTimings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Swimming");
                });
#pragma warning restore 612, 618
        }
    }
}
